# -*- coding: utf-8 -*-
"""kNN tut4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYjybcoKLxa-cw5GClmMDRD7NToNcvIq
"""

import pandas as pd
df=pd.read_csv('/content/Network_Intrusion_Dataset(1).csv')
df.head()

list(df.columns)
#no of rows and columns

df.shape

import plotly.express as px
#Construct a bar graph for Traffic_Type target variable
Traffic_Type_fig = px.bar(df, x = 'Traffic_Type', title = "Traffic Types")

#Construct a bar graph for Intrusion_Traffic_Type target variable
Intrusion_Traffic_Type_fig = px.bar(df, x ='Intrusion_Traffic_Type', title =" Attacks Types")

#Construct a bivariate bar graph for both target variable
Intrusion_Types_Per_Traffic_fig = px.bar(df,x ='Traffic_Type', color = 'Intrusion_Traffic_Type', title = "Attack Types In Intrusion Traffic", color_discrete_sequence = px.colors.qualitative.Vivid)

#Remove the bar outline by setting the marker.line.width attribute to 0
Traffic_Type_fig.update_traces(dict(marker_line_width=0))
Intrusion_Traffic_Type_fig.update_traces(dict(marker_line_width=0))
Intrusion_Types_Per_Traffic_fig.update_traces(dict(marker_line_width=0))

#Plot all constructed bar graphs
Traffic_Type_fig.show()
Intrusion_Traffic_Type_fig.show()
Intrusion_Types_Per_Traffic_fig.show()

df.info()

df.describe().transpose()

df = df.drop(columns=df.loc[:, 'Packets_Rx_Dropped':'Packets_Tx_Errors'].columns)
df = df.drop(columns=df.loc[:, 'Delta_Packets_Rx_Dropped':'Delta_Packets_Tx_Errors'].columns)
df = df.drop(['Is_Valid', 'Table_ID', 'Max_Size'], axis=1)
df.describe(include="all").transpose()

df.isna().sum()/len(df)*100

df.to_csv(r'/content/Prepared_Network_Intrusion_Dataset.csv', index = False)

import pandas as pd
#loading the new dataset
df=pd.read_csv('/content/diabetes (1).csv')
df.head()

#splitting the data into target and feature variables
feature_cols=['']